## This is a full **NumPy Exploration**

In [34]:
import numpy as np #this is a standard naming convention

**List can have variable datatypes but Array can only have one kind of a datatype**

In [35]:
integers_list = [10,20,30,40,50]
print(integers_list)
print(type(integers_list))

[10, 20, 30, 40, 50]
<class 'list'>


**Converting a list to a NumPy array**

In [36]:
integers = np.array(integers_list) #this is the method to convert list into a NumPy array
print(integers)
print(type(integers))

[10 20 30 40 50]
<class 'numpy.ndarray'>


**Accessing the values of the array**

In [37]:
print(integers[0]) #this will print the zeroth position value of the array
print(integers[-1]) #this will print the last element of the array

10
50


**Changing the value of the index and changing the type**

In [38]:
integers[0] = 21.5
print(integers) #this is convert the integer value as array can only have one datatype
print((integers.dtype)) #this is to check the data type of the values of the array
print('\n')

integers_small = np.array(integers, dtype = np.int8) #this changes the type of the values 
                                                     #to int8
print(integers_small)

print(integers.nbytes) #this is to check the number of bytes occupied by the array
print(integers_small.nbytes) #changing the type can save a lot of memory

[21 20 30 40 50]
int64


[21 20 30 40 50]
40
5


**Numpy is smart and will choose automatically a datatype for the array if we don't explicitely pass the dtype arguement**

In [39]:
floats = np.array([1.1,1.2,1.3,1.4])
print(floats.dtype)

float64


**1D Array = Vector, 2D Array = Matrix 3D Array = Tensor**

In [40]:
numbers = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #this is a 2D array [[a,b],[c,d]]
print(numbers)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Accessing the value of a 2D array**

In [41]:
print(numbers[0,0]) #will print the first value of the first array of a 2D array
print(numbers[-1,-2]) #will print the "2nd last value" of the "last array" of a 2D array

1
9


**Creating a tensor**

In [45]:
three_d_array = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]]) 
print(three_d_array)
print(three_d_array[0,0,2]) #prints from zeroth array, and inside that the zeroth array 
                            #and 3rd element

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


**Check the dimension of the array**

In [47]:
np.ndim(three_d_array)

3

**The list is converted to the numpy array with the most used datatype in the list**

In [49]:
complex_list = [1,2.1,3.35,'hello','world','numpy','array']
complex_array = np.array(complex_list)

print(complex_array) #here all the elements will become string datatypes 
print(complex_array.dtype)

['1' '2.1' '3.35' 'hello' 'world' 'numpy' 'array']
<U32


**Tuple: It is an immutable list (the elements cannot be changed)**

In [57]:
tuple_numbers = (1,2,3,4,5)
print(tuple_numbers)
print(type(tuple_numbers))

#map funtion returns an iterator when applied to a list or a tuple 
element_type = list(map(type, tuple_numbers))
print(element_type)

(1, 2, 3, 4, 5)
<class 'tuple'>
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


**Manually creating arrays can consume time. We can create arrays by NumPy built-in methods**

In [59]:
instant_array = np.arange(10)
print(instant_array)

instant_array_1 = np.arange(1,10)
print(instant_array_1)

instant_array_set = np.arange(1,151,2)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
